---

- name: Add the user 'tycho' with a bash shell, appending the group 'wheel'
  ansible.builtin.user:
    name: tycho
    shell: /bin/bash
    groups: wheel
    append: yes

- name: Set password for user 'tycho'
  ansible.builtin.user:
    name: tycho
    update_password: always
    password: "{{ tychoheimdall|password_hash('sha512') }}"

- name: Generate an OpenSSH keypair for user 'tycho' with the default values (521 bits, ed25519)
  community.crypto.openssh_keypair:
    path: ~tycho/.ssh/id_ed25519
    type: ed25519

- name: Generate an OpenSSH keypair for user 'root' with the default values (521 bits, ed25519)
  community.crypto.openssh_keypair:
    path: ~/.ssh/id_ed25519
    type: ed25519

- name: Make sure public keys are set present at user 'root'
  ansible.posix.authorized_key:
    user: root
    state: present
    key: "{{ pubkey_item }}"
  with_file:
    - public_keys/M2729-doctert-id_rsa.pub
    - public_keys/apollo-tycho-id_ed25519.pub
    - public_keys/freya-tycho-id_ed25519.pub
    - public_keys/heimdall-tycho-id_ed25519.pub
    - public_keys/ns-tycho-id_ed25519.pub
    - public_keys/tycho_apollo-id_ed25519.pub
  loop_control:
    loop_var: pubkey_item

- name: Ensure root ssh login is not possible
  ansible.builtin.lineinfile:
    path: /etc/selinux/config
    regexp: '^#PermitRootLogin'
    line: PermitRootLogin no

- name: Ensure ssh login with key is possible
  ansible.builtin.lineinfile:
    path: /etc/selinux/config
    regexp: '^#PubkeyAuthentication'
    line: PubkeyAuthentication yes

- name: Set password for user 'root'
  ansible.builtin.user:
    name: root
    update_password: always
    password: "{{ rootpwd|password_hash('sha512') }}"

...
